name: CI

on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name ${{ secrets.USERNAME }}
          git config --global user.email ${{ secrets.EMAIL }}

      - name: Make changes and push
        run: |
          echo " " >> README.md
          git add .
          git commit -m "Updates made"
          git push
          
      - name: Additional actions
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
